seed: 42
device: cuda:3

paths:
  data_path:   /home/minchan/electric/data/
  output_path: /home/minchan/electric/output/without_units

data:
  exclude_general_vars: ['altitude_mm', 'units_qt']
  exclude_climlag_vars: ['rain_qt']

xgboost:
  optuna_search: False
  n_trials: 5

  default:
    n_estimators: 3000
    early_stopping_rounds: 50
    ########################
    eta: 0.01
    #
    max_depth: 12
    min_child_weight: 771.65
    #
    gamma: 0.03061
    colsample_bytree: 0.60883
    # 
    alpha: 0.0196957
    lambda:  0.00181321
    #
    highslope: 0.3492
    ########################

  optimize:
    ########################
    eta: False
    #
    max_depth: False
    min_child_weight: False
    #
    gamma: False
    colsample_bytree: False
    #
    alpha: False
    lambda: False
    #
    highslope: False
    ########################

  suggest:
    ########################
    eta:
      type: float
      range: [0.0001, 0.1]
      log: True
    highslope:  # this is fixed
      type: float
      range: [0.3, 0.6]
      log: False
    ########################
    max_depth:
      type: int
      range: [10,14]
      step: 1
    min_child_weight:
      type: float
      range: [256, 1024]
      log: True
    ########################
    gamma:
      type: float
      range: [0.0001, 1.0]
      log: True
    colsample_bytree:
      type: float
      range: [0.6, 1.0]
      log: False
    ########################
    alpha:
      type: float
      range: [0.012, 0.12]
      log: True
    lambda:
      type: float
      range: [0.001, 0.01]
      log: True
    ########################